const serviceCatalog = {
  Plant: {
    Housekeeping: [
      "Floor Cleaning",
      "Desk Cleaning",
      "Washroom Cleaning",
      "Peripheral Cleaning",
      "Chair Cleaning",
      "Sofa Cleaning",
      "Others",
    ],
    Plumbing: [
      "Washroom",
      "Floor Area",
      "External Plumbing",
      "Water Leakage",
      "Tank Cleaning",
      "Drain Choke",
      "Others",
    ],
    "Pest Control": [
      "General Pest Control",
      "Snake Control",
      "Honeybee Control",
      "Bedbug",
      "Insect Control",
      "Others",
    ],
    Carpenter: ["Door", "Window", "Sliding-Balcony", "Furniture", "Others"],
    Electrical: [
      "Fan",
      "Power Failure",
      "Lights",
      "Additional Work",
      "AC",
      "Gyser",
      "Others",
    ],
    Water: ["Drinking Water", "Flush Water", "Kitchen Water", "Raw Water", "STP", "Others"],
    Others: ["Others"],
  },
  Guesthouse: {
    Housekeeping: [
      "Floor Cleaning",
      "Desk Cleaning",
      "Washroom Cleaning",
      "Peripheral Cleaning",
      "Chair Cleaning",
      "Sofa Cleaning",
      "Others",
    ],
    Plumbing: [
      "Washroom",
      "Floor Area",
      "External Plumbing",
      "Water Leakage",
      "Tank Cleaning",
      "Drain Choke",
      "Others",
    ],
    "Pest Control": [
      "General Pest Control",
      "Snake Control",
      "Honeybee Control",
      "Bedbug",
      "Insect Control",
      "Others",
    ],
    Carpenter: ["Door", "Window", "Sliding-Balcony", "Furniture", "Others"],
    Electrical: [
      "Fan",
      "Power Failure",
      "Lights",
      "Additional Work",
      "AC",
      "Gyser",
      "Others",
    ],
    Water: ["Drinking Water", "Flush Water", "Kitchen Water", "Raw Water", "STP", "Others"],
    Others: ["Others"],
  },
  Colony: {
    Housekeeping: [
      "Floor Cleaning",
      "Desk Cleaning",
      "Washroom Cleaning",
      "Peripheral Cleaning",
      "Chair Cleaning",
      "Sofa Cleaning",
      "Others",
    ],
    Plumbing: [
      "Washroom",
      "Floor Area",
      "External Plumbing",
      "Water Leakage",
      "Tank Cleaning",
      "Drain Choke",
      "Others",
    ],
    "Pest Control": [
      "General Pest Control",
      "Snake Control",
      "Honeybee Control",
      "Bedbug",
      "Insect Control",
      "Others",
    ],
    Carpenter: ["Door", "Window", "Sliding-Balcony", "Furniture", "Others"],
    Electrical: [
      "Fan",
      "Power Failure",
      "Lights",
      "Additional Work",
      "AC",
      "Gyser",
      "Others",
    ],
    Water: ["Drinking Water", "Flush Water", "Kitchen Water", "Raw Water", "STP", "Others"],
    Others: ["Others"],
  },
  Hostel: {
    Housekeeping: [
      "Floor Cleaning",
      "Desk Cleaning",
      "Washroom Cleaning",
      "Peripheral Cleaning",
      "Chair Cleaning",
      "Sofa Cleaning",
      "Others",
    ],
    Plumbing: [
      "Washroom",
      "Floor Area",
      "External Plumbing",
      "Water Leakage",
      "Tank Cleaning",
      "Drain Choke",
      "Others",
    ],
    "Pest Control": [
      "General Pest Control",
      "Snake Control",
      "Honeybee Control",
      "Bedbug",
      "Insect Control",
      "Others",
    ],
    Carpenter: ["Door", "Window", "Sliding-Balcony", "Furniture", "Others"],
    Electrical: ["Fan", "Power Failure", "Lights", "Additional Work", "AC", "Gyser", "Others"],
    Water: ["Drinking Water", "Flush Water", "Kitchen Water", "Raw Water", "STP", "Others"],
    Accommodation: ["Book Hostel Room", "Others"],
    Others: ["Others"],
  },
};

const locationCatalog = {
  Plant: [
    "Plant Admin Block",
    "Boiler Section",
    "Control Room",
    "Workshop Bay",
    "Production Line 1",
    "Raw Material Yard",
  ],
  Guesthouse: [
    "Guesthouse Reception",
    "Room 101",
    "Room 102",
    "Dining Hall",
    "Kitchen Area",
    "Conference Lounge",
  ],
  Colony: [
    "Colony Gate",
    "Block A",
    "Block B",
    "Community Hall",
    "Park Area",
    "Water Tank Zone",
  ],
  Hostel: [
    "Hostel Reception",
    "Hostel Lobby",
    "Room 101",
    "Room 102",
    "Dining Area",
    "Common Room",
  ],
};

const siteColors = {
  Plant: "#c62828",
  Guesthouse: "#212121",
  Colony: "#8e0000",
  Hostel: "#c62828",
};

module.exports = {
  locationCatalog,
  serviceCatalog,
  siteColors,
};
